#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf

url=https://drive.officialmirror.workers.dev/ccache/ccache.tar.gz

cd /tmp # Where to download cccahe
time rclone copy gdrive:/ccache/ . -P 
time tar xf ccache.tar.gz
find ccache.tar.gz -delete
