#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf

url=https://cheems.mirrorbomt.workers.dev/ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
find ccache.tar.gz -delete
