#!/bin/bash

MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=11.0

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name ItsVixano
git config --global user.email vixanonew@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/JamieHoSzeYui/device_xiaomi_sm6250-common device/xiaomi/sm6250-common
git clone https://github.com/JamieHoSzeYui/vendor_xiaomi_sm6250-common vendor/xiaomi/sm6250-common 
git clone https://github.com/JamieHoSzeYui/vendor_xiaomi_miatoll vendor/xiaomi/miatoll 
git clone https://github.com/JamieHoSzeYui/device_xiaomi_miatoll device/xiaomi/miatoll 
git clone --depth=1 --single-branch https://github.com/ctwoon/Rinka_curtana kernel/xiaomi/sm6250
