#!/bin/bash

cd /tmp

date=`date +%Y%m%d`
name=`ccache-$date`

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com $name 1 # Compression level 1, its enough

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
time rclone copy $name.tar.gz gdrive:/ccache/ -P # apon is my rclone config name, ccache/ci2 is where ccache will be saved in my cloud, use yours one
